### ISSUE TITLE
can't download data_large_panoptic.tar successfully

### ISSUE THREAD

**Issue by Damehou** [htzheng/CM-GAN-Inpainting#13]

**Comment by sthse7en** [comment]
Same issue, any progress？

**Comment by htzheng** [comment]
Hi @Damehou @sthse7en, please check the new link for the file. Thanks a lot.

https://www.dropbox.com/scl/fi/ub9zhaa1eaw72zcwdm2jp/data_large_panoptic.tar?rlkey=r0ohjh4s8kiaslu8lh2cm9nsu&st=s8mufn32&dl=0
