### ISSUE TITLE
Questions about the object masks

### ISSUE THREAD

**Issue by yqjiang6** [htzheng/CM-GAN-Inpainting#6]
Hi! This is an amazing work in image inpainting, and I'm really interesting the method to generate masks described in your paper. The problem is that when generating masks, object masks are first sampled. However, this repo only provides 4 object masks. Could you provide more samples and the method to construct the object masks? Thank you!

**Comment by htzheng** [comment]
Thank you for your interest in our work! We used the ProFill (ECCV'20) object mask dataset to generate the random object masks. The entire object mask dataset can be downloaded here https://zengxianyu.github.io/iic/#object-masks

**Comment by yqjiang6** [comment]
Thanks for your reply! It helps me a lot!
